export function getPreviewShellHtml(previewUrl: string, fontAwesomeCssHref: string, cspSource: string): string {
  const nonce = createNonce();
  const previewOrigin = new URL(previewUrl).origin;

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    `  <meta http-equiv="Content-Security-Policy" content="default-src \'none\'; frame-src ${escapeHtmlAttribute(previewOrigin)}; script-src \'nonce-${nonce}\'; style-src ${escapeHtmlAttribute(cspSource)} \'unsafe-inline\'; font-src ${escapeHtmlAttribute(cspSource)};">`,
    `  <link rel="stylesheet" href="${escapeHtmlAttribute(fontAwesomeCssHref)}">`,
    '  <style>',
    '    :root {',
    '      --ca-shell-toolbar-height: 32px;',
    '      --ca-shell-toolbar-bg: #1f1f1f;',
    '      --ca-shell-toolbar-border: rgba(255, 255, 255, 0.08);',
    '      --ca-shell-toolbar-text: #f7fafc;',
    '      --ca-shell-toolbar-hover: rgba(255, 255, 255, 0.14);',
    '      --ca-shell-toolbar-active: #2b7fff;',
    '      --ca-shell-toolbar-active-border: #1458e0;',
    '    }',
    '',
    '    html, body {',
    '      margin: 0;',
    '      padding: 0 !important;',
    '      width: 100%;',
    '      height: 100%;',
    '      position: fixed;',
    '      inset: 0;',
    '      overflow: hidden;',
    '      background: transparent;',
    '    }',
    '',
    '    body.vscode-body {',
    '      padding: 0 !important;',
    '    }',
    '',
    '    html, body, iframe {',
    '      box-sizing: border-box;',
    '    }',
    '',
    '    .ca-shell-toolbar {',
    '      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
    '    }',
    '',
    '    .ca-shell-toolbar *,',
    '    .ca-shell-toolbar *::before,',
    '    .ca-shell-toolbar *::after {',
    '      box-sizing: border-box;',
    '    }',
    '',
    '    .ca-shell-toolbar {',
    '      position: fixed;',
    '      top: 0;',
    '      left: 0;',
    '      right: 0;',
    '      height: var(--ca-shell-toolbar-height);',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 0;',
    '      padding: 0;',
    '      background: var(--ca-shell-toolbar-bg);',
    '      color: var(--ca-shell-toolbar-text);',
    '      border-bottom: 1px solid var(--ca-shell-toolbar-border);',
    '      z-index: 2;',
    '      overflow: hidden;',
    '    }',
    '',
    '    .ca-shell-toolbar__group {',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 0;',
    '      min-width: 0;',
    '    }',
    '',
    '    .ca-shell-toolbar__group--actions {',
    '      margin-left: auto;',
    '    }',
    '',
    '    .ca-shell-button {',
    '      height: var(--ca-shell-toolbar-height);',
    '      border: 1px solid transparent;',
    '      border-radius: 0;',
    '      background: transparent;',
    '      color: inherit;',
    '      padding: 0 10px;',
    '      font-size: 12px;',
    '      font-weight: 600;',
    '      display: inline-flex;',
    '      align-items: center;',
    '      justify-content: center;',
    '      gap: 8px;',
    '      cursor: pointer;',
    '    }',
    '',
    '    .ca-shell-button i {',
    '      width: 14px;',
    '      height: 14px;',
    '      font-size: 14px;',
    '      flex: none;',
    '      pointer-events: none;',
    '    }',
    '',
    '    .ca-shell-button i.fa-solid {',
    '      font-family: "Font Awesome 7 Free";',
    '      font-weight: 900;',
    '    }',
    '',
    '    .ca-shell-button--tool,',
    '    .ca-shell-button--quiet {',
    '      width: var(--ca-shell-toolbar-height);',
    '      padding: 0;',
    '      gap: 0;',
    '    }',
    '',
    '    .ca-shell-button:hover,',
    '    .ca-shell-button:focus-visible {',
    '      background: var(--ca-shell-toolbar-hover);',
    '      outline: none;',
    '    }',
    '',
    '    .ca-shell-button[aria-pressed="true"] {',
    '      background: var(--ca-shell-toolbar-active);',
    '      border-color: var(--ca-shell-toolbar-active-border);',
    '    }',
    '',
    '    .ca-shell-button--primary {',
    '      background: var(--ca-shell-toolbar-active);',
    '      color: white;',
    '      border-color: var(--ca-shell-toolbar-active-border);',
    '      padding: 0 12px;',
    '    }',
    '',
    '    .ca-shell-button--primary:hover,',
    '    .ca-shell-button--primary:focus-visible {',
    '      background: #368cff;',
    '    }',
    '',
    '    iframe {',
    '      position: fixed;',
    '      top: var(--ca-shell-toolbar-height);',
    '      left: 0;',
    '      right: 0;',
    '      bottom: 0;',
    '      width: auto;',
    '      height: auto;',
    '      min-width: 100%;',
    '      min-height: calc(100% - var(--ca-shell-toolbar-height));',
    '      border: 0;',
    '      display: block;',
    '      background: transparent;',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    `  ${getShellToolbarHtml()}`,
    `  <iframe id="copilot-annotation-preview-frame" src="${escapeHtmlAttribute(previewUrl)}" referrerpolicy="no-referrer"></iframe>`,
    `  <script nonce="${nonce}">`,
    '    const vscode = acquireVsCodeApi();',
    '    const frame = document.getElementById("copilot-annotation-preview-frame");',
    '    const toolButtons = Array.from(document.querySelectorAll("[data-tool]"));',
    '    const actionButtons = Array.from(document.querySelectorAll("[data-action]"));',
    `    const previewOrigin = ${JSON.stringify(previewOrigin)};`,
    '',
    '    function postHostCommand(command, extra = {}) {',
    '      if (!frame.contentWindow) {',
    '        return;',
    '      }',
    '',
    '      frame.contentWindow.postMessage({',
    '        type: "copilotAnnotationHostCommand",',
    '        command,',
    '        ...extra',
    '      }, previewOrigin);',
    '    }',
    '',
    '    function updateToolbarState(message) {',
    '      toolButtons.forEach((button) => {',
    '        button.setAttribute("aria-pressed", String(button.dataset.tool === message.tool));',
    '      });',
    '    }',
    '',
    '    toolButtons.forEach((button) => {',
    '      button.addEventListener("click", () => {',
    '        const tool = button.dataset.tool;',
    '        if (!tool) {',
    '          return;',
    '        }',
    '        postHostCommand("setTool", { tool });',
    '      });',
    '    });',
    '',
    '    actionButtons.forEach((button) => {',
    '      button.addEventListener("click", () => {',
    '        const action = button.dataset.action;',
    '        if (action === "view") {',
    '          postHostCommand("viewFeedback");',
    '          return;',
    '        }',
    '        if (action === "clear") {',
    '          postHostCommand("clearAnnotations");',
    '          return;',
    '        }',
    '        if (action === "send") {',
    '          postHostCommand("sendFeedback");',
    '        }',
    '      });',
    '    });',
    '',
    '    frame.addEventListener("load", () => {',
    '      window.setTimeout(() => {',
    '        postHostCommand("requestToolbarState");',
    '      }, 50);',
    '    });',
    '',
    '    window.addEventListener("message", (event) => {',
    '      if (frame.contentWindow && event.source === frame.contentWindow) {',
    '        if (event.origin !== previewOrigin) {',
    '          return;',
    '        }',
    '',
    '        const message = event.data;',
    '        if (!message || message.source !== "copilot-annotation-runtime") {',
    '          return;',
    '        }',
    '',
    '        if (message.type === "toolbarState") {',
    '          updateToolbarState(message);',
    '        }',
    '',
    '        vscode.postMessage(message);',
    '        return;',
    '      }',
    '',
    '      if (!frame.contentWindow) {',
    '        return;',
    '      }',
    '',
    '      frame.contentWindow.postMessage(event.data, previewOrigin);',
    '    });',
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');
}

function createNonce(): string {
  return Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
}

function getShellToolbarHtml(): string {
  return [
    '<div class="ca-shell-toolbar" role="toolbar" aria-label="Copilot Annotation Toolbar">',
    '  <div class="ca-shell-toolbar__group">',
    `    <button type="button" class="ca-shell-button ca-shell-button--tool" data-tool="text" aria-pressed="true" aria-label="Text selection" title="Text selection">${getShellIconHtml('text')}</button>`,
    `    <button type="button" class="ca-shell-button ca-shell-button--tool" data-tool="element" aria-pressed="false" aria-label="Element selection" title="Element selection">${getShellIconHtml('element')}</button>`,
    `    <button type="button" class="ca-shell-button ca-shell-button--tool" data-tool="multi" aria-pressed="false" aria-label="Multi-select" title="Multi-select">${getShellIconHtml('multi')}</button>`,
    `    <button type="button" class="ca-shell-button ca-shell-button--tool" data-tool="area" aria-pressed="false" aria-label="Area selection" title="Area selection">${getShellIconHtml('area')}</button>`,
    '  </div>',
    '  <div class="ca-shell-toolbar__group ca-shell-toolbar__group--actions">',
    `    <button type="button" class="ca-shell-button ca-shell-button--quiet" data-action="view" aria-label="View feedback" title="View feedback">${getShellIconHtml('view')}</button>`,
    `    <button type="button" class="ca-shell-button ca-shell-button--quiet" data-action="clear" aria-label="Clear annotations" title="Clear annotations">${getShellIconHtml('clear')}</button>`,
    `    <button type="button" class="ca-shell-button ca-shell-button--primary" data-action="send" title="Send Feedback"><span>Send Feedback</span>${getShellIconHtml('send')}</button>`,
    '  </div>',
    '</div>'
  ].join('\n');
}

function getShellIconHtml(icon: 'text' | 'element' | 'multi' | 'area' | 'view' | 'clear' | 'send'): string {
  switch (icon) {
    case 'text':
      return '<i class="fa-solid fa-i-cursor" aria-hidden="true"></i>';
    case 'element':
      return '<i class="fa-solid fa-arrow-pointer" aria-hidden="true"></i>';
    case 'multi':
      return '<i class="fa-solid fa-layer-group" aria-hidden="true"></i>';
    case 'area':
      return '<i class="fa-solid fa-crop" aria-hidden="true"></i>';
    case 'view':
      return '<i class="fa-solid fa-eye" aria-hidden="true"></i>';
    case 'clear':
      return '<i class="fa-solid fa-trash-can" aria-hidden="true"></i>';
    case 'send':
      return '<i class="fa-solid fa-paper-plane" aria-hidden="true"></i>';
  }
}

function escapeHtmlAttribute(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}